version: '3.7'

services:
  postgresql:
    image: postgres:12-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ydima3
      POSTGRES_PASSWORD: 3333
    volumes:
      - postgres-data:/usr/local/var/postgres

volumes:
  postgres-data:
    driver: local
